import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { installResource } from "../src/resources/dispatch.js";
import { renderGeneratedFile } from "../src/rendering/structured-file.js";
import { bash, shell, zsh } from "../src/api/shell.js";
import { files } from "../src/api/config.js";
import type { CommandResult, Runner } from "../src/api/types.js";

class UnusedRunner implements Runner {
  async run(): Promise<CommandResult> {
    throw new Error("Runner should not be used by generated files");
  }
}

describe("structured files", () => {
  it("overwrites by default", () => {
    expect(files.json("~/.config/example.json", {}).ifExists).toBe("overwrite");
  });

  it.each([
    ["toml", 'name = "workstation"\n'],
    ["yaml", "name: workstation\n"],
    ["json", '{\n  "name": "workstation"\n}\n'],
  ] as const)("renders %s", (format, expected) => {
    expect(
      renderGeneratedFile({
        kind: "generated-file",
        target: "/tmp/config",
        format,
        value: { name: "workstation" },
        ifExists: "update",
      }),
    ).toBe(expected);
  });

  it("renders valid JSONC with a generated header", () => {
    const output = renderGeneratedFile({
      kind: "generated-file",
      target: "/tmp/config.jsonc",
      format: "jsonc",
      value: { enabled: true },
      ifExists: "update",
    });
    expect(output).toContain("// Generated by Workstation");
    expect(output).toContain('"enabled": true');
  });

  it("protects unmanaged files with update and preserves them with ignore", async () => {
    const root = await mkdtemp(join(tmpdir(), "workstation-files-"));
    const target = join(root, "config.json");
    await writeFile(target, "personal\n");
    const base = {
      kind: "generated-file" as const,
      target,
      format: "json" as const,
      value: { managed: true },
    };

    await expect(
      installResource({ ...base, ifExists: "update" }, new UnusedRunner()),
    ).rejects.toThrow("exists with different content");
    await expect(
      installResource({ ...base, ifExists: "ignore" }, new UnusedRunner()),
    ).resolves.toMatchObject({ matches: true });
    expect(await readFile(target, "utf8")).toBe("personal\n");
  });

  it("builds deterministic Zsh environment, paths, aliases, and hook files", () => {
    const resource = zsh.zprofile(
      [
        shell.prependPath(shell.home(".local/bin"), "/opt/homebrew/bin"),
        shell.export("EDITOR", "zed --wait"),
        shell.when(shell.condition.commandExists("mise"), [
          shell.eval(shell.command("mise", ["activate", "zsh", "--shims"])),
        ]),
        shell.alias("ll", "eza -lah --git"),
      ],
      { ifExists: "overwrite" },
    );

    expect(resource.target).toBe("~/.zprofile");
    const rendered = renderGeneratedFile(resource);
    expect(rendered).toContain('export PATH="${HOME}/.local/bin":\'/opt/homebrew/bin\':"$PATH"');
    expect(rendered).toContain("export EDITOR='zed --wait'");
    expect(rendered).toContain("alias ll='eza -lah --git'");
    expect(rendered).toContain("if command -v 'mise' >/dev/null 2>&1; then");
  });

  it("uses the shared shell AST to generate Bash files", () => {
    const resource = bash.bashrc([
      shell.export("EDITOR", "code --wait"),
      shell.source(shell.home(".local/bash/common.sh"), { ifExists: true }),
    ]);

    expect(resource).toMatchObject({
      target: "~/.bashrc",
      format: "bash",
      ifExists: "overwrite",
    });
    expect(renderGeneratedFile(resource)).toContain("export EDITOR='code --wait'");
    expect(renderGeneratedFile(resource)).toContain(
      'if [[ -r "${HOME}/.local/bash/common.sh" ]]; then source "${HOME}/.local/bash/common.sh"; fi',
    );
  });
});
