import { stringify as stringifyToml } from "smol-toml";
import { stringify as stringifyYaml } from "yaml";
import type { GeneratedFileResource } from "../api/types.js";
import { mergeDotenv } from "./dotenv.js";

/** Render structured or shell content with a final newline; preserve pre-rendered JSONC comments. */
export function renderGeneratedFile(resource: GeneratedFileResource): string {
  switch (resource.format) {
    case "dotenv": return mergeDotenv("", resource.value);
    case "toml":
      if (!isRecord(resource.value)) throw new Error("TOML configuration must be an object");
      return ensureNewline(stringifyToml(resource.value));
    case "yaml":
      return ensureNewline(stringifyYaml(resource.value, { lineWidth: 0 }));
    case "json":
      return `${JSON.stringify(resource.value, null, 2)}\n`;
    case "jsonc":
      if (resource.renderedContent !== undefined) return ensureNewline(resource.renderedContent);
      return `// Generated by Workstation. JSONC accepts standard JSON values.\n${JSON.stringify(resource.value, null, 2)}\n`;
    case "zsh":
    case "bash":
    case "sh":
      if (typeof resource.value !== "string") throw new Error("Zsh configuration must be a string");
      return ensureNewline(resource.value);
  }
}

/** Append one final newline when the rendered text does not already have one. */
function ensureNewline(value: string): string {
  return value.endsWith("\n") ? value : `${value}\n`;
}

/** Narrow an unknown value to a non-null, non-array object. */
function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
